import Head from "next/head";
import { Box } from "@chakra-ui/react";

import Navbar from "./Navbar";

interface LayoutProps {
  children: React.ReactNode;
  title?: string;
}

function Layout({ children, title }: LayoutProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <Navbar />
      <Box as="main">{children}</Box>
    </>
  );
}

export default Layout;
